// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package com.caibowen.prma.api.proto;

public final class Event {
  private Event() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventPOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.caibowen.prma.api.proto.EventPO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required uint64 time_created = 2;</code>
     */
    boolean hasTimeCreated();
    /**
     * <code>required uint64 time_created = 2;</code>
     */
    long getTimeCreated();

    /**
     * <code>required uint32 level = 3;</code>
     */
    boolean hasLevel();
    /**
     * <code>required uint32 level = 3;</code>
     */
    int getLevel();

    /**
     * <code>required string logger_name = 4;</code>
     */
    boolean hasLoggerName();
    /**
     * <code>required string logger_name = 4;</code>
     */
    String getLoggerName();
    /**
     * <code>required string logger_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getLoggerNameBytes();

    /**
     * <code>required string thread_name = 5;</code>
     */
    boolean hasThreadName();
    /**
     * <code>required string thread_name = 5;</code>
     */
    String getThreadName();
    /**
     * <code>required string thread_name = 5;</code>
     */
    com.google.protobuf.ByteString
        getThreadNameBytes();

    /**
     * <code>required string fmt_msg = 6;</code>
     */
    boolean hasFmtMsg();
    /**
     * <code>required string fmt_msg = 6;</code>
     */
    String getFmtMsg();
    /**
     * <code>required string fmt_msg = 6;</code>
     */
    com.google.protobuf.ByteString
        getFmtMsgBytes();

    /**
     * <code>required .com.caibowen.prma.api.proto.StackTracePO caller_st = 7;</code>
     */
    boolean hasCallerSt();
    /**
     * <code>required .com.caibowen.prma.api.proto.StackTracePO caller_st = 7;</code>
     */
    StackTrace.StackTracePO getCallerSt();
    /**
     * <code>required .com.caibowen.prma.api.proto.StackTracePO caller_st = 7;</code>
     */
    StackTrace.StackTracePOOrBuilder getCallerStOrBuilder();

    /**
     * <code>optional uint64 reserved = 8;</code>
     */
    boolean hasReserved();
    /**
     * <code>optional uint64 reserved = 8;</code>
     */
    long getReserved();

    /**
     * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
     */
    java.util.List<EventPO.Property>
        getPropertiesList();
    /**
     * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
     */
    EventPO.Property getProperties(int index);
    /**
     * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
     */
    int getPropertiesCount();
    /**
     * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
     */
    java.util.List<? extends EventPO.PropertyOrBuilder>
        getPropertiesOrBuilderList();
    /**
     * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
     */
    EventPO.PropertyOrBuilder getPropertiesOrBuilder(
            int index);

    /**
     * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
     */
    java.util.List<Exception.ExceptionPO>
        getExceptionsList();
    /**
     * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
     */
    Exception.ExceptionPO getExceptions(int index);
    /**
     * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
     */
    int getExceptionsCount();
    /**
     * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
     */
    java.util.List<? extends Exception.ExceptionPOOrBuilder>
        getExceptionsOrBuilderList();
    /**
     * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
     */
    Exception.ExceptionPOOrBuilder getExceptionsOrBuilder(
            int index);

    /**
     * <code>repeated string markers = 11;</code>
     */
    com.google.protobuf.ProtocolStringList
        getMarkersList();
    /**
     * <code>repeated string markers = 11;</code>
     */
    int getMarkersCount();
    /**
     * <code>repeated string markers = 11;</code>
     */
    String getMarkers(int index);
    /**
     * <code>repeated string markers = 11;</code>
     */
    com.google.protobuf.ByteString
        getMarkersBytes(int index);

    /**
     * <code>required uint64 flag = 12;</code>
     */
    boolean hasFlag();
    /**
     * <code>required uint64 flag = 12;</code>
     */
    long getFlag();
  }
  /**
   * Protobuf type {@code com.caibowen.prma.api.proto.EventPO}
   */
  public static final class EventPO extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.caibowen.prma.api.proto.EventPO)
      EventPOOrBuilder {
    // Use EventPO.newBuilder() to construct.
    private EventPO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EventPO(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EventPO defaultInstance;
    public static EventPO getDefaultInstance() {
      return defaultInstance;
    }

    public EventPO getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EventPO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timeCreated_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              level_ = input.readUInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              loggerName_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              threadName_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              fmtMsg_ = bs;
              break;
            }
            case 58: {
              StackTrace.StackTracePO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = callerSt_.toBuilder();
              }
              callerSt_ = input.readMessage(StackTrace.StackTracePO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(callerSt_);
                callerSt_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              reserved_ = input.readUInt64();
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                properties_ = new java.util.ArrayList<Property>();
                mutable_bitField0_ |= 0x00000100;
              }
              properties_.add(input.readMessage(Property.PARSER, extensionRegistry));
              break;
            }
            case 82: {
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
                exceptions_ = new java.util.ArrayList<Exception.ExceptionPO>();
                mutable_bitField0_ |= 0x00000200;
              }
              exceptions_.add(input.readMessage(Exception.ExceptionPO.PARSER, extensionRegistry));
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
                markers_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000400;
              }
              markers_.add(bs);
              break;
            }
            case 96: {
              bitField0_ |= 0x00000100;
              flag_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          properties_ = java.util.Collections.unmodifiableList(properties_);
        }
        if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
          exceptions_ = java.util.Collections.unmodifiableList(exceptions_);
        }
        if (((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
          markers_ = markers_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Event.internal_static_com_caibowen_prma_api_proto_EventPO_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Event.internal_static_com_caibowen_prma_api_proto_EventPO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EventPO.class, Builder.class);
    }

    public static com.google.protobuf.Parser<EventPO> PARSER =
        new com.google.protobuf.AbstractParser<EventPO>() {
      public EventPO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventPO(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<EventPO> getParserForType() {
      return PARSER;
    }

    public interface PropertyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.caibowen.prma.api.proto.EventPO.Property)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string map_key = 1;</code>
       */
      boolean hasMapKey();
      /**
       * <code>required string map_key = 1;</code>
       */
      String getMapKey();
      /**
       * <code>required string map_key = 1;</code>
       */
      com.google.protobuf.ByteString
          getMapKeyBytes();

      /**
       * <code>required bytes map_value = 2;</code>
       */
      boolean hasMapValue();
      /**
       * <code>required bytes map_value = 2;</code>
       */
      com.google.protobuf.ByteString getMapValue();
    }
    /**
     * Protobuf type {@code com.caibowen.prma.api.proto.EventPO.Property}
     */
    public static final class Property extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:com.caibowen.prma.api.proto.EventPO.Property)
        PropertyOrBuilder {
      // Use Property.newBuilder() to construct.
      private Property(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Property(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Property defaultInstance;
      public static Property getDefaultInstance() {
        return defaultInstance;
      }

      public Property getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Property(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                mapKey_ = bs;
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                mapValue_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Event.internal_static_com_caibowen_prma_api_proto_EventPO_Property_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Event.internal_static_com_caibowen_prma_api_proto_EventPO_Property_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Property.class, Builder.class);
      }

      public static com.google.protobuf.Parser<Property> PARSER =
          new com.google.protobuf.AbstractParser<Property>() {
        public Property parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Property(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<Property> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int MAP_KEY_FIELD_NUMBER = 1;
      private Object mapKey_;
      /**
       * <code>required string map_key = 1;</code>
       */
      public boolean hasMapKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string map_key = 1;</code>
       */
      public String getMapKey() {
        Object ref = mapKey_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mapKey_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string map_key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMapKeyBytes() {
        Object ref = mapKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mapKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int MAP_VALUE_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString mapValue_;
      /**
       * <code>required bytes map_value = 2;</code>
       */
      public boolean hasMapValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes map_value = 2;</code>
       */
      public com.google.protobuf.ByteString getMapValue() {
        return mapValue_;
      }

      private void initFields() {
        mapKey_ = "";
        mapValue_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasMapKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasMapValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getMapKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, mapValue_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getMapKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, mapValue_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Property parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Property parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Property parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Property parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Property parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Property parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Property parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Property parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Property parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Property parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Property prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.caibowen.prma.api.proto.EventPO.Property}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.caibowen.prma.api.proto.EventPO.Property)
          PropertyOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Event.internal_static_com_caibowen_prma_api_proto_EventPO_Property_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Event.internal_static_com_caibowen_prma_api_proto_EventPO_Property_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Property.class, Builder.class);
        }

        // Construct using com.caibowen.prma.api.proto.Event.EventPO.Property.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          mapKey_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          mapValue_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Event.internal_static_com_caibowen_prma_api_proto_EventPO_Property_descriptor;
        }

        public Property getDefaultInstanceForType() {
          return Property.getDefaultInstance();
        }

        public Property build() {
          Property result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Property buildPartial() {
          Property result = new Property(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.mapKey_ = mapKey_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.mapValue_ = mapValue_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Property) {
            return mergeFrom((Property)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Property other) {
          if (other == Property.getDefaultInstance()) return this;
          if (other.hasMapKey()) {
            bitField0_ |= 0x00000001;
            mapKey_ = other.mapKey_;
            onChanged();
          }
          if (other.hasMapValue()) {
            setMapValue(other.getMapValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasMapKey()) {
            
            return false;
          }
          if (!hasMapValue()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Property parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Property) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private Object mapKey_ = "";
        /**
         * <code>required string map_key = 1;</code>
         */
        public boolean hasMapKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string map_key = 1;</code>
         */
        public String getMapKey() {
          Object ref = mapKey_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              mapKey_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string map_key = 1;</code>
         */
        public com.google.protobuf.ByteString
            getMapKeyBytes() {
          Object ref = mapKey_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            mapKey_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string map_key = 1;</code>
         */
        public Builder setMapKey(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          mapKey_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string map_key = 1;</code>
         */
        public Builder clearMapKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          mapKey_ = getDefaultInstance().getMapKey();
          onChanged();
          return this;
        }
        /**
         * <code>required string map_key = 1;</code>
         */
        public Builder setMapKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          mapKey_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString mapValue_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes map_value = 2;</code>
         */
        public boolean hasMapValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bytes map_value = 2;</code>
         */
        public com.google.protobuf.ByteString getMapValue() {
          return mapValue_;
        }
        /**
         * <code>required bytes map_value = 2;</code>
         */
        public Builder setMapValue(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          mapValue_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes map_value = 2;</code>
         */
        public Builder clearMapValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          mapValue_ = getDefaultInstance().getMapValue();
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.caibowen.prma.api.proto.EventPO.Property)
      }

      static {
        defaultInstance = new Property(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.caibowen.prma.api.proto.EventPO.Property)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required uint64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int TIME_CREATED_FIELD_NUMBER = 2;
    private long timeCreated_;
    /**
     * <code>required uint64 time_created = 2;</code>
     */
    public boolean hasTimeCreated() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 time_created = 2;</code>
     */
    public long getTimeCreated() {
      return timeCreated_;
    }

    public static final int LEVEL_FIELD_NUMBER = 3;
    private int level_;
    /**
     * <code>required uint32 level = 3;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 level = 3;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int LOGGER_NAME_FIELD_NUMBER = 4;
    private Object loggerName_;
    /**
     * <code>required string logger_name = 4;</code>
     */
    public boolean hasLoggerName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string logger_name = 4;</code>
     */
    public String getLoggerName() {
      Object ref = loggerName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          loggerName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string logger_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLoggerNameBytes() {
      Object ref = loggerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        loggerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int THREAD_NAME_FIELD_NUMBER = 5;
    private Object threadName_;
    /**
     * <code>required string thread_name = 5;</code>
     */
    public boolean hasThreadName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string thread_name = 5;</code>
     */
    public String getThreadName() {
      Object ref = threadName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          threadName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string thread_name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getThreadNameBytes() {
      Object ref = threadName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        threadName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FMT_MSG_FIELD_NUMBER = 6;
    private Object fmtMsg_;
    /**
     * <code>required string fmt_msg = 6;</code>
     */
    public boolean hasFmtMsg() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string fmt_msg = 6;</code>
     */
    public String getFmtMsg() {
      Object ref = fmtMsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fmtMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fmt_msg = 6;</code>
     */
    public com.google.protobuf.ByteString
        getFmtMsgBytes() {
      Object ref = fmtMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fmtMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CALLER_ST_FIELD_NUMBER = 7;
    private StackTrace.StackTracePO callerSt_;
    /**
     * <code>required .com.caibowen.prma.api.proto.StackTracePO caller_st = 7;</code>
     */
    public boolean hasCallerSt() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required .com.caibowen.prma.api.proto.StackTracePO caller_st = 7;</code>
     */
    public StackTrace.StackTracePO getCallerSt() {
      return callerSt_;
    }
    /**
     * <code>required .com.caibowen.prma.api.proto.StackTracePO caller_st = 7;</code>
     */
    public StackTrace.StackTracePOOrBuilder getCallerStOrBuilder() {
      return callerSt_;
    }

    public static final int RESERVED_FIELD_NUMBER = 8;
    private long reserved_;
    /**
     * <code>optional uint64 reserved = 8;</code>
     */
    public boolean hasReserved() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint64 reserved = 8;</code>
     */
    public long getReserved() {
      return reserved_;
    }

    public static final int PROPERTIES_FIELD_NUMBER = 9;
    private java.util.List<Property> properties_;
    /**
     * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
     */
    public java.util.List<Property> getPropertiesList() {
      return properties_;
    }
    /**
     * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
     */
    public java.util.List<? extends PropertyOrBuilder>
        getPropertiesOrBuilderList() {
      return properties_;
    }
    /**
     * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
     */
    public int getPropertiesCount() {
      return properties_.size();
    }
    /**
     * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
     */
    public Property getProperties(int index) {
      return properties_.get(index);
    }
    /**
     * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
     */
    public PropertyOrBuilder getPropertiesOrBuilder(
        int index) {
      return properties_.get(index);
    }

    public static final int EXCEPTIONS_FIELD_NUMBER = 10;
    private java.util.List<Exception.ExceptionPO> exceptions_;
    /**
     * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
     */
    public java.util.List<Exception.ExceptionPO> getExceptionsList() {
      return exceptions_;
    }
    /**
     * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
     */
    public java.util.List<? extends Exception.ExceptionPOOrBuilder>
        getExceptionsOrBuilderList() {
      return exceptions_;
    }
    /**
     * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
     */
    public int getExceptionsCount() {
      return exceptions_.size();
    }
    /**
     * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
     */
    public Exception.ExceptionPO getExceptions(int index) {
      return exceptions_.get(index);
    }
    /**
     * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
     */
    public Exception.ExceptionPOOrBuilder getExceptionsOrBuilder(
        int index) {
      return exceptions_.get(index);
    }

    public static final int MARKERS_FIELD_NUMBER = 11;
    private com.google.protobuf.LazyStringList markers_;
    /**
     * <code>repeated string markers = 11;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMarkersList() {
      return markers_;
    }
    /**
     * <code>repeated string markers = 11;</code>
     */
    public int getMarkersCount() {
      return markers_.size();
    }
    /**
     * <code>repeated string markers = 11;</code>
     */
    public String getMarkers(int index) {
      return markers_.get(index);
    }
    /**
     * <code>repeated string markers = 11;</code>
     */
    public com.google.protobuf.ByteString
        getMarkersBytes(int index) {
      return markers_.getByteString(index);
    }

    public static final int FLAG_FIELD_NUMBER = 12;
    private long flag_;
    /**
     * <code>required uint64 flag = 12;</code>
     */
    public boolean hasFlag() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required uint64 flag = 12;</code>
     */
    public long getFlag() {
      return flag_;
    }

    private void initFields() {
      id_ = 0L;
      timeCreated_ = 0L;
      level_ = 0;
      loggerName_ = "";
      threadName_ = "";
      fmtMsg_ = "";
      callerSt_ = StackTrace.StackTracePO.getDefaultInstance();
      reserved_ = 0L;
      properties_ = java.util.Collections.emptyList();
      exceptions_ = java.util.Collections.emptyList();
      markers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      flag_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeCreated()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLoggerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasThreadName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFmtMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCallerSt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFlag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCallerSt().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPropertiesCount(); i++) {
        if (!getProperties(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getExceptionsCount(); i++) {
        if (!getExceptions(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, timeCreated_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getLoggerNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getThreadNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getFmtMsgBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, callerSt_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt64(8, reserved_);
      }
      for (int i = 0; i < properties_.size(); i++) {
        output.writeMessage(9, properties_.get(i));
      }
      for (int i = 0; i < exceptions_.size(); i++) {
        output.writeMessage(10, exceptions_.get(i));
      }
      for (int i = 0; i < markers_.size(); i++) {
        output.writeBytes(11, markers_.getByteString(i));
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt64(12, flag_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timeCreated_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getLoggerNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getThreadNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getFmtMsgBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, callerSt_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, reserved_);
      }
      for (int i = 0; i < properties_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, properties_.get(i));
      }
      for (int i = 0; i < exceptions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, exceptions_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < markers_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(markers_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getMarkersList().size();
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(12, flag_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static EventPO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EventPO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EventPO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EventPO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EventPO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EventPO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static EventPO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static EventPO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static EventPO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EventPO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(EventPO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.caibowen.prma.api.proto.EventPO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.caibowen.prma.api.proto.EventPO)
        EventPOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Event.internal_static_com_caibowen_prma_api_proto_EventPO_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Event.internal_static_com_caibowen_prma_api_proto_EventPO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EventPO.class, Builder.class);
      }

      // Construct using com.caibowen.prma.api.proto.Event.EventPO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCallerStFieldBuilder();
          getPropertiesFieldBuilder();
          getExceptionsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        timeCreated_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        loggerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        threadName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        fmtMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        if (callerStBuilder_ == null) {
          callerSt_ = StackTrace.StackTracePO.getDefaultInstance();
        } else {
          callerStBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        reserved_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        if (propertiesBuilder_ == null) {
          properties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          propertiesBuilder_.clear();
        }
        if (exceptionsBuilder_ == null) {
          exceptions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
        } else {
          exceptionsBuilder_.clear();
        }
        markers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000400);
        flag_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Event.internal_static_com_caibowen_prma_api_proto_EventPO_descriptor;
      }

      public EventPO getDefaultInstanceForType() {
        return EventPO.getDefaultInstance();
      }

      public EventPO build() {
        EventPO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public EventPO buildPartial() {
        EventPO result = new EventPO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timeCreated_ = timeCreated_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.loggerName_ = loggerName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.threadName_ = threadName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.fmtMsg_ = fmtMsg_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (callerStBuilder_ == null) {
          result.callerSt_ = callerSt_;
        } else {
          result.callerSt_ = callerStBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.reserved_ = reserved_;
        if (propertiesBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            properties_ = java.util.Collections.unmodifiableList(properties_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.properties_ = properties_;
        } else {
          result.properties_ = propertiesBuilder_.build();
        }
        if (exceptionsBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200)) {
            exceptions_ = java.util.Collections.unmodifiableList(exceptions_);
            bitField0_ = (bitField0_ & ~0x00000200);
          }
          result.exceptions_ = exceptions_;
        } else {
          result.exceptions_ = exceptionsBuilder_.build();
        }
        if (((bitField0_ & 0x00000400) == 0x00000400)) {
          markers_ = markers_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000400);
        }
        result.markers_ = markers_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000100;
        }
        result.flag_ = flag_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EventPO) {
          return mergeFrom((EventPO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EventPO other) {
        if (other == EventPO.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTimeCreated()) {
          setTimeCreated(other.getTimeCreated());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasLoggerName()) {
          bitField0_ |= 0x00000008;
          loggerName_ = other.loggerName_;
          onChanged();
        }
        if (other.hasThreadName()) {
          bitField0_ |= 0x00000010;
          threadName_ = other.threadName_;
          onChanged();
        }
        if (other.hasFmtMsg()) {
          bitField0_ |= 0x00000020;
          fmtMsg_ = other.fmtMsg_;
          onChanged();
        }
        if (other.hasCallerSt()) {
          mergeCallerSt(other.getCallerSt());
        }
        if (other.hasReserved()) {
          setReserved(other.getReserved());
        }
        if (propertiesBuilder_ == null) {
          if (!other.properties_.isEmpty()) {
            if (properties_.isEmpty()) {
              properties_ = other.properties_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensurePropertiesIsMutable();
              properties_.addAll(other.properties_);
            }
            onChanged();
          }
        } else {
          if (!other.properties_.isEmpty()) {
            if (propertiesBuilder_.isEmpty()) {
              propertiesBuilder_.dispose();
              propertiesBuilder_ = null;
              properties_ = other.properties_;
              bitField0_ = (bitField0_ & ~0x00000100);
              propertiesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPropertiesFieldBuilder() : null;
            } else {
              propertiesBuilder_.addAllMessages(other.properties_);
            }
          }
        }
        if (exceptionsBuilder_ == null) {
          if (!other.exceptions_.isEmpty()) {
            if (exceptions_.isEmpty()) {
              exceptions_ = other.exceptions_;
              bitField0_ = (bitField0_ & ~0x00000200);
            } else {
              ensureExceptionsIsMutable();
              exceptions_.addAll(other.exceptions_);
            }
            onChanged();
          }
        } else {
          if (!other.exceptions_.isEmpty()) {
            if (exceptionsBuilder_.isEmpty()) {
              exceptionsBuilder_.dispose();
              exceptionsBuilder_ = null;
              exceptions_ = other.exceptions_;
              bitField0_ = (bitField0_ & ~0x00000200);
              exceptionsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getExceptionsFieldBuilder() : null;
            } else {
              exceptionsBuilder_.addAllMessages(other.exceptions_);
            }
          }
        }
        if (!other.markers_.isEmpty()) {
          if (markers_.isEmpty()) {
            markers_ = other.markers_;
            bitField0_ = (bitField0_ & ~0x00000400);
          } else {
            ensureMarkersIsMutable();
            markers_.addAll(other.markers_);
          }
          onChanged();
        }
        if (other.hasFlag()) {
          setFlag(other.getFlag());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasTimeCreated()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        if (!hasLoggerName()) {
          
          return false;
        }
        if (!hasThreadName()) {
          
          return false;
        }
        if (!hasFmtMsg()) {
          
          return false;
        }
        if (!hasCallerSt()) {
          
          return false;
        }
        if (!hasFlag()) {
          
          return false;
        }
        if (!getCallerSt().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getPropertiesCount(); i++) {
          if (!getProperties(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getExceptionsCount(); i++) {
          if (!getExceptions(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EventPO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EventPO) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required uint64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private long timeCreated_ ;
      /**
       * <code>required uint64 time_created = 2;</code>
       */
      public boolean hasTimeCreated() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 time_created = 2;</code>
       */
      public long getTimeCreated() {
        return timeCreated_;
      }
      /**
       * <code>required uint64 time_created = 2;</code>
       */
      public Builder setTimeCreated(long value) {
        bitField0_ |= 0x00000002;
        timeCreated_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 time_created = 2;</code>
       */
      public Builder clearTimeCreated() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timeCreated_ = 0L;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>required uint32 level = 3;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 level = 3;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required uint32 level = 3;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000004;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 level = 3;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = 0;
        onChanged();
        return this;
      }

      private Object loggerName_ = "";
      /**
       * <code>required string logger_name = 4;</code>
       */
      public boolean hasLoggerName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string logger_name = 4;</code>
       */
      public String getLoggerName() {
        Object ref = loggerName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            loggerName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string logger_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLoggerNameBytes() {
        Object ref = loggerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          loggerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string logger_name = 4;</code>
       */
      public Builder setLoggerName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        loggerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string logger_name = 4;</code>
       */
      public Builder clearLoggerName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        loggerName_ = getDefaultInstance().getLoggerName();
        onChanged();
        return this;
      }
      /**
       * <code>required string logger_name = 4;</code>
       */
      public Builder setLoggerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        loggerName_ = value;
        onChanged();
        return this;
      }

      private Object threadName_ = "";
      /**
       * <code>required string thread_name = 5;</code>
       */
      public boolean hasThreadName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string thread_name = 5;</code>
       */
      public String getThreadName() {
        Object ref = threadName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            threadName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string thread_name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getThreadNameBytes() {
        Object ref = threadName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          threadName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string thread_name = 5;</code>
       */
      public Builder setThreadName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        threadName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string thread_name = 5;</code>
       */
      public Builder clearThreadName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        threadName_ = getDefaultInstance().getThreadName();
        onChanged();
        return this;
      }
      /**
       * <code>required string thread_name = 5;</code>
       */
      public Builder setThreadNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        threadName_ = value;
        onChanged();
        return this;
      }

      private Object fmtMsg_ = "";
      /**
       * <code>required string fmt_msg = 6;</code>
       */
      public boolean hasFmtMsg() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string fmt_msg = 6;</code>
       */
      public String getFmtMsg() {
        Object ref = fmtMsg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fmtMsg_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string fmt_msg = 6;</code>
       */
      public com.google.protobuf.ByteString
          getFmtMsgBytes() {
        Object ref = fmtMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fmtMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fmt_msg = 6;</code>
       */
      public Builder setFmtMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        fmtMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fmt_msg = 6;</code>
       */
      public Builder clearFmtMsg() {
        bitField0_ = (bitField0_ & ~0x00000020);
        fmtMsg_ = getDefaultInstance().getFmtMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string fmt_msg = 6;</code>
       */
      public Builder setFmtMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        fmtMsg_ = value;
        onChanged();
        return this;
      }

      private StackTrace.StackTracePO callerSt_ = StackTrace.StackTracePO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          StackTrace.StackTracePO, StackTrace.StackTracePO.Builder, StackTrace.StackTracePOOrBuilder> callerStBuilder_;
      /**
       * <code>required .com.caibowen.prma.api.proto.StackTracePO caller_st = 7;</code>
       */
      public boolean hasCallerSt() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required .com.caibowen.prma.api.proto.StackTracePO caller_st = 7;</code>
       */
      public StackTrace.StackTracePO getCallerSt() {
        if (callerStBuilder_ == null) {
          return callerSt_;
        } else {
          return callerStBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.caibowen.prma.api.proto.StackTracePO caller_st = 7;</code>
       */
      public Builder setCallerSt(StackTrace.StackTracePO value) {
        if (callerStBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          callerSt_ = value;
          onChanged();
        } else {
          callerStBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>required .com.caibowen.prma.api.proto.StackTracePO caller_st = 7;</code>
       */
      public Builder setCallerSt(
          StackTrace.StackTracePO.Builder builderForValue) {
        if (callerStBuilder_ == null) {
          callerSt_ = builderForValue.build();
          onChanged();
        } else {
          callerStBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>required .com.caibowen.prma.api.proto.StackTracePO caller_st = 7;</code>
       */
      public Builder mergeCallerSt(StackTrace.StackTracePO value) {
        if (callerStBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              callerSt_ != StackTrace.StackTracePO.getDefaultInstance()) {
            callerSt_ =
              StackTrace.StackTracePO.newBuilder(callerSt_).mergeFrom(value).buildPartial();
          } else {
            callerSt_ = value;
          }
          onChanged();
        } else {
          callerStBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>required .com.caibowen.prma.api.proto.StackTracePO caller_st = 7;</code>
       */
      public Builder clearCallerSt() {
        if (callerStBuilder_ == null) {
          callerSt_ = StackTrace.StackTracePO.getDefaultInstance();
          onChanged();
        } else {
          callerStBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>required .com.caibowen.prma.api.proto.StackTracePO caller_st = 7;</code>
       */
      public StackTrace.StackTracePO.Builder getCallerStBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getCallerStFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.caibowen.prma.api.proto.StackTracePO caller_st = 7;</code>
       */
      public StackTrace.StackTracePOOrBuilder getCallerStOrBuilder() {
        if (callerStBuilder_ != null) {
          return callerStBuilder_.getMessageOrBuilder();
        } else {
          return callerSt_;
        }
      }
      /**
       * <code>required .com.caibowen.prma.api.proto.StackTracePO caller_st = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          StackTrace.StackTracePO, StackTrace.StackTracePO.Builder, StackTrace.StackTracePOOrBuilder>
          getCallerStFieldBuilder() {
        if (callerStBuilder_ == null) {
          callerStBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              StackTrace.StackTracePO, StackTrace.StackTracePO.Builder, StackTrace.StackTracePOOrBuilder>(
                  getCallerSt(),
                  getParentForChildren(),
                  isClean());
          callerSt_ = null;
        }
        return callerStBuilder_;
      }

      private long reserved_ ;
      /**
       * <code>optional uint64 reserved = 8;</code>
       */
      public boolean hasReserved() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional uint64 reserved = 8;</code>
       */
      public long getReserved() {
        return reserved_;
      }
      /**
       * <code>optional uint64 reserved = 8;</code>
       */
      public Builder setReserved(long value) {
        bitField0_ |= 0x00000080;
        reserved_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 reserved = 8;</code>
       */
      public Builder clearReserved() {
        bitField0_ = (bitField0_ & ~0x00000080);
        reserved_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<Property> properties_ =
        java.util.Collections.emptyList();
      private void ensurePropertiesIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          properties_ = new java.util.ArrayList<Property>(properties_);
          bitField0_ |= 0x00000100;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Property, Property.Builder, PropertyOrBuilder> propertiesBuilder_;

      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public java.util.List<Property> getPropertiesList() {
        if (propertiesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(properties_);
        } else {
          return propertiesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public int getPropertiesCount() {
        if (propertiesBuilder_ == null) {
          return properties_.size();
        } else {
          return propertiesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public Property getProperties(int index) {
        if (propertiesBuilder_ == null) {
          return properties_.get(index);
        } else {
          return propertiesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public Builder setProperties(
          int index, Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.set(index, value);
          onChanged();
        } else {
          propertiesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public Builder setProperties(
          int index, Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.set(index, builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public Builder addProperties(Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.add(value);
          onChanged();
        } else {
          propertiesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public Builder addProperties(
          int index, Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.add(index, value);
          onChanged();
        } else {
          propertiesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public Builder addProperties(
          Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.add(builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public Builder addProperties(
          int index, Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.add(index, builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public Builder addAllProperties(
          Iterable<? extends Property> values) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, properties_);
          onChanged();
        } else {
          propertiesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public Builder clearProperties() {
        if (propertiesBuilder_ == null) {
          properties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          propertiesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public Builder removeProperties(int index) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.remove(index);
          onChanged();
        } else {
          propertiesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public Property.Builder getPropertiesBuilder(
          int index) {
        return getPropertiesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public PropertyOrBuilder getPropertiesOrBuilder(
          int index) {
        if (propertiesBuilder_ == null) {
          return properties_.get(index);  } else {
          return propertiesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public java.util.List<? extends PropertyOrBuilder>
           getPropertiesOrBuilderList() {
        if (propertiesBuilder_ != null) {
          return propertiesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(properties_);
        }
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public Property.Builder addPropertiesBuilder() {
        return getPropertiesFieldBuilder().addBuilder(
            Property.getDefaultInstance());
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public Property.Builder addPropertiesBuilder(
          int index) {
        return getPropertiesFieldBuilder().addBuilder(
            index, Property.getDefaultInstance());
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.EventPO.Property properties = 9;</code>
       */
      public java.util.List<Property.Builder>
           getPropertiesBuilderList() {
        return getPropertiesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Property, Property.Builder, PropertyOrBuilder>
          getPropertiesFieldBuilder() {
        if (propertiesBuilder_ == null) {
          propertiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Property, Property.Builder, PropertyOrBuilder>(
                  properties_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          properties_ = null;
        }
        return propertiesBuilder_;
      }

      private java.util.List<Exception.ExceptionPO> exceptions_ =
        java.util.Collections.emptyList();
      private void ensureExceptionsIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          exceptions_ = new java.util.ArrayList<Exception.ExceptionPO>(exceptions_);
          bitField0_ |= 0x00000200;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Exception.ExceptionPO, Exception.ExceptionPO.Builder, Exception.ExceptionPOOrBuilder> exceptionsBuilder_;

      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public java.util.List<Exception.ExceptionPO> getExceptionsList() {
        if (exceptionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(exceptions_);
        } else {
          return exceptionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public int getExceptionsCount() {
        if (exceptionsBuilder_ == null) {
          return exceptions_.size();
        } else {
          return exceptionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public Exception.ExceptionPO getExceptions(int index) {
        if (exceptionsBuilder_ == null) {
          return exceptions_.get(index);
        } else {
          return exceptionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public Builder setExceptions(
          int index, Exception.ExceptionPO value) {
        if (exceptionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExceptionsIsMutable();
          exceptions_.set(index, value);
          onChanged();
        } else {
          exceptionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public Builder setExceptions(
          int index, Exception.ExceptionPO.Builder builderForValue) {
        if (exceptionsBuilder_ == null) {
          ensureExceptionsIsMutable();
          exceptions_.set(index, builderForValue.build());
          onChanged();
        } else {
          exceptionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public Builder addExceptions(Exception.ExceptionPO value) {
        if (exceptionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExceptionsIsMutable();
          exceptions_.add(value);
          onChanged();
        } else {
          exceptionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public Builder addExceptions(
          int index, Exception.ExceptionPO value) {
        if (exceptionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExceptionsIsMutable();
          exceptions_.add(index, value);
          onChanged();
        } else {
          exceptionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public Builder addExceptions(
          Exception.ExceptionPO.Builder builderForValue) {
        if (exceptionsBuilder_ == null) {
          ensureExceptionsIsMutable();
          exceptions_.add(builderForValue.build());
          onChanged();
        } else {
          exceptionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public Builder addExceptions(
          int index, Exception.ExceptionPO.Builder builderForValue) {
        if (exceptionsBuilder_ == null) {
          ensureExceptionsIsMutable();
          exceptions_.add(index, builderForValue.build());
          onChanged();
        } else {
          exceptionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public Builder addAllExceptions(
          Iterable<? extends Exception.ExceptionPO> values) {
        if (exceptionsBuilder_ == null) {
          ensureExceptionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, exceptions_);
          onChanged();
        } else {
          exceptionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public Builder clearExceptions() {
        if (exceptionsBuilder_ == null) {
          exceptions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
          onChanged();
        } else {
          exceptionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public Builder removeExceptions(int index) {
        if (exceptionsBuilder_ == null) {
          ensureExceptionsIsMutable();
          exceptions_.remove(index);
          onChanged();
        } else {
          exceptionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public Exception.ExceptionPO.Builder getExceptionsBuilder(
          int index) {
        return getExceptionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public Exception.ExceptionPOOrBuilder getExceptionsOrBuilder(
          int index) {
        if (exceptionsBuilder_ == null) {
          return exceptions_.get(index);  } else {
          return exceptionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public java.util.List<? extends Exception.ExceptionPOOrBuilder>
           getExceptionsOrBuilderList() {
        if (exceptionsBuilder_ != null) {
          return exceptionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(exceptions_);
        }
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public Exception.ExceptionPO.Builder addExceptionsBuilder() {
        return getExceptionsFieldBuilder().addBuilder(
            Exception.ExceptionPO.getDefaultInstance());
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public Exception.ExceptionPO.Builder addExceptionsBuilder(
          int index) {
        return getExceptionsFieldBuilder().addBuilder(
            index, Exception.ExceptionPO.getDefaultInstance());
      }
      /**
       * <code>repeated .com.caibowen.prma.api.proto.ExceptionPO exceptions = 10;</code>
       */
      public java.util.List<Exception.ExceptionPO.Builder>
           getExceptionsBuilderList() {
        return getExceptionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Exception.ExceptionPO, Exception.ExceptionPO.Builder, Exception.ExceptionPOOrBuilder>
          getExceptionsFieldBuilder() {
        if (exceptionsBuilder_ == null) {
          exceptionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Exception.ExceptionPO, Exception.ExceptionPO.Builder, Exception.ExceptionPOOrBuilder>(
                  exceptions_,
                  ((bitField0_ & 0x00000200) == 0x00000200),
                  getParentForChildren(),
                  isClean());
          exceptions_ = null;
        }
        return exceptionsBuilder_;
      }

      private com.google.protobuf.LazyStringList markers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMarkersIsMutable() {
        if (!((bitField0_ & 0x00000400) == 0x00000400)) {
          markers_ = new com.google.protobuf.LazyStringArrayList(markers_);
          bitField0_ |= 0x00000400;
         }
      }
      /**
       * <code>repeated string markers = 11;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getMarkersList() {
        return markers_.getUnmodifiableView();
      }
      /**
       * <code>repeated string markers = 11;</code>
       */
      public int getMarkersCount() {
        return markers_.size();
      }
      /**
       * <code>repeated string markers = 11;</code>
       */
      public String getMarkers(int index) {
        return markers_.get(index);
      }
      /**
       * <code>repeated string markers = 11;</code>
       */
      public com.google.protobuf.ByteString
          getMarkersBytes(int index) {
        return markers_.getByteString(index);
      }
      /**
       * <code>repeated string markers = 11;</code>
       */
      public Builder setMarkers(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMarkersIsMutable();
        markers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string markers = 11;</code>
       */
      public Builder addMarkers(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMarkersIsMutable();
        markers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string markers = 11;</code>
       */
      public Builder addAllMarkers(
          Iterable<String> values) {
        ensureMarkersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, markers_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string markers = 11;</code>
       */
      public Builder clearMarkers() {
        markers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string markers = 11;</code>
       */
      public Builder addMarkersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMarkersIsMutable();
        markers_.add(value);
        onChanged();
        return this;
      }

      private long flag_ ;
      /**
       * <code>required uint64 flag = 12;</code>
       */
      public boolean hasFlag() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required uint64 flag = 12;</code>
       */
      public long getFlag() {
        return flag_;
      }
      /**
       * <code>required uint64 flag = 12;</code>
       */
      public Builder setFlag(long value) {
        bitField0_ |= 0x00000800;
        flag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 flag = 12;</code>
       */
      public Builder clearFlag() {
        bitField0_ = (bitField0_ & ~0x00000800);
        flag_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.caibowen.prma.api.proto.EventPO)
    }

    static {
      defaultInstance = new EventPO(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.caibowen.prma.api.proto.EventPO)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_caibowen_prma_api_proto_EventPO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_caibowen_prma_api_proto_EventPO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_caibowen_prma_api_proto_EventPO_Property_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_caibowen_prma_api_proto_EventPO_Property_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013Event.proto\022\033com.caibowen.prma.api.pro" +
      "to\032\020StackTrace.proto\032\017Exception.proto\"\225\003" +
      "\n\007EventPO\022\n\n\002id\030\001 \002(\004\022\024\n\014time_created\030\002 " +
      "\002(\004\022\r\n\005level\030\003 \002(\r\022\023\n\013logger_name\030\004 \002(\t\022" +
      "\023\n\013thread_name\030\005 \002(\t\022\017\n\007fmt_msg\030\006 \002(\t\022<\n" +
      "\tcaller_st\030\007 \002(\0132).com.caibowen.prma.api" +
      ".proto.StackTracePO\022\020\n\010reserved\030\010 \001(\004\022A\n" +
      "\nproperties\030\t \003(\0132-.com.caibowen.prma.ap" +
      "i.proto.EventPO.Property\022<\n\nexceptions\030\n" +
      " \003(\0132(.com.caibowen.prma.api.proto.Excep",
      "tionPO\022\017\n\007markers\030\013 \003(\t\022\014\n\004flag\030\014 \002(\004\032.\n" +
      "\010Property\022\017\n\007map_key\030\001 \002(\t\022\021\n\tmap_value\030" +
      "\002 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          StackTrace.getDescriptor(),
          Exception.getDescriptor(),
        }, assigner);
    internal_static_com_caibowen_prma_api_proto_EventPO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_caibowen_prma_api_proto_EventPO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_caibowen_prma_api_proto_EventPO_descriptor,
        new String[] { "Id", "TimeCreated", "Level", "LoggerName", "ThreadName", "FmtMsg", "CallerSt", "Reserved", "Properties", "Exceptions", "Markers", "Flag", });
    internal_static_com_caibowen_prma_api_proto_EventPO_Property_descriptor =
      internal_static_com_caibowen_prma_api_proto_EventPO_descriptor.getNestedTypes().get(0);
    internal_static_com_caibowen_prma_api_proto_EventPO_Property_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_caibowen_prma_api_proto_EventPO_Property_descriptor,
        new String[] { "MapKey", "MapValue", });
    StackTrace.getDescriptor();
    Exception.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
