// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogLevel.proto

package com.caibowen.prma.api.proto;

public final class LogLevel {
  private LogLevel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.caibowen.prma.api.proto.LogLevelPO}
   */
  public enum LogLevelPO
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ERROR = 0;</code>
     */
    ERROR(0, 0),
    /**
     * <code>WARN = 1;</code>
     */
    WARN(1, 1),
    /**
     * <code>INFO = 2;</code>
     */
    INFO(2, 2),
    /**
     * <code>DEBUG = 3;</code>
     */
    DEBUG(3, 3),
    /**
     * <code>TRACE = 4;</code>
     */
    TRACE(4, 4),
    ;

    /**
     * <code>ERROR = 0;</code>
     */
    public static final int ERROR_VALUE = 0;
    /**
     * <code>WARN = 1;</code>
     */
    public static final int WARN_VALUE = 1;
    /**
     * <code>INFO = 2;</code>
     */
    public static final int INFO_VALUE = 2;
    /**
     * <code>DEBUG = 3;</code>
     */
    public static final int DEBUG_VALUE = 3;
    /**
     * <code>TRACE = 4;</code>
     */
    public static final int TRACE_VALUE = 4;


    public final int getNumber() { return value; }

    public static LogLevelPO valueOf(int value) {
      switch (value) {
        case 0: return ERROR;
        case 1: return WARN;
        case 2: return INFO;
        case 3: return DEBUG;
        case 4: return TRACE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LogLevelPO>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<LogLevelPO>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LogLevelPO>() {
            public LogLevelPO findValueByNumber(int number) {
              return LogLevelPO.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return LogLevel.getDescriptor().getEnumTypes().get(0);
    }

    private static final LogLevelPO[] VALUES = values();

    public static LogLevelPO valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private LogLevelPO(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.caibowen.prma.api.proto.LogLevelPO)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016LogLevel.proto\022\033com.caibowen.prma.api." +
      "proto*A\n\nLogLevelPO\022\t\n\005ERROR\020\000\022\010\n\004WARN\020\001" +
      "\022\010\n\004INFO\020\002\022\t\n\005DEBUG\020\003\022\t\n\005TRACE\020\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
